const images = {
  HeaderBackground: require("../Picture/BG.png"),
  chat: require("../Picture/chat.png"),
  sigleout: require("../Picture/signout.png"),
  witness: require("../Picture/witness.png"),
  cross: require("../Picture/icon-Cross/bt.png"),
  banner: require("../Picture/Banner/banner.png"),
  icon_search: require("../Picture/ico_Search.png"),
  logo_urbox: require("../Picture/Logos_Brand/logoUrboxFinal1.png"),
  logo_the_coffee_house: require("../Picture/Logos_Brand/icon.png"),
  logo_mobifone: require("../Picture/Logos_Brand/mobifone.png"),
  logo_vinid: require("../Picture/Logos_Brand/vinId.png"),
  logo_bee: require("../Picture/Logos_Brand/appLogoBe.png"),
  logo_dienmayxanh: require("../Picture/Logos_Brand/appLogoDienMayXanh.png"),
  icon1: require("../Picture/ico1.png"),
  icon2: require("../Picture/ico2.png"),
  icon3: require("../Picture/ico3.png"),
  icon4: require("../Picture/ico4.png"),
  banner1: require("../Picture/Layer1.png"),
  icon_home: require("../Picture/BottomNvgBar/home.png"),
  icon_voucher: require("../Picture/BottomNvgBar/voucher.png"),
  icon_account: require("../Picture/BottomNvgBar/account.png"),
  icon_wallet: require("../Picture/BottomNvgBar/wallet.png"),
  detail: require('../Picture/Voucher_default.png'),
  times: require('../Picture/ico_calendar.png'),
  frame_item : require('../Picture/Frame_Item.png'),
  pro1: require('../Picture/product/pro1.png'),
  pro2: require('../Picture/product/pro2.png'),
  pro3: require('../Picture/product/pro1.png'),
  plus1: require('../Picture/plus.png')
};

export default images;
